### ISSUE TITLE
Contributing, goal/vision of the project.

### ISSUE THREAD

**Issue by alexanderjeurissen** [Tehnix/spaceneovim#4]
As a Neovim user that has switched multiple times between my own Neovim config and SpaceMacs I really like this effort 👍 

I'd love to help contribute but some things are still unclear for me.
1. What's the progress in the conversion process from spacevim -> spaceneovim
2. What work still needs to be done ?
3.  How do you plan to facilitate discussion about what plugins to introduce and what neovim equivalent's to use for certain plugins ?
4. Seeing as you recently landed a commit titled: "adding vim support" how does this project relate to the original fork ? Is the goal to replace SpaceVim in the future when feature parity is reached ?

I think the later is really important, I'd like to prevent two separate projects whilst we could have a united effort in bringing spacemacs to neovim/vim.

**Comment by Tehnix** [comment]
Excellent questions/concerns! and I might have been a bit premature in sharing this repository before setting up some more clear goal posts (and the goals have also changed slightly since I began). 

1. Spacevim itself was not particularly tied to regular vim (and should work in neovim), but before beginning my rewrite I thought I was going to have to use a lot of neovim specific API calls and such - that turned out not to be the case. 
2. Currently smoothing out the install process and providing a nicer UX is on the plan, along with getting all the layers done. The layers are really the most critical one, but is luckily *super* easy to do - you just need to know what plugins you want.
3. With regards to discussions 
    - Currently I imagine discussions will be separated into the two repositories. Core discussions such as install, updating and such goes in this (the [spaceneovim](https://github.com/Tehnix/spaceneovim)) repository and discussiosn with regards to layers go in the layers ([spaceneovim-layers](https://github.com/Tehnix/spaceneovim-layers)) repository
    - Faciliatating neovim vs regular vim plugins is still up for discussion. Currently for things like the syntax checker you'd probably use `+syntax-checking/syntastic` for regular vim and `+syntax-checking/neomake` for neovim. Once you go into languages though, it could either be hidden behind `has('nvim')` or perhaps a more clear separation like say `+lang/n-haskell` for neovim and `+lang/haskell` for regular vim, although I'd prefer not to split them up too much. 
4. Before getting familiar with vimscript/viml I assumed that supporting vim and neovim at the same time would be a lot of hassle, and would rather just focus on one thing - this though proved a lot easier than my initial estimate and therefore I decided to add vim support back again. There are a few `has('nvim')` calls here and there but all in all it's not so bad

I think you're very right that the latter concerns are quite important! Being able to have more community effort behind making the layers work perfectly is super important, and I'm contemplating renaming back to `spacevim`, since supporting both proved so trivial.

**Comment by Tehnix** [comment]
Oh, and with regards to the big difference between spacevim and SpaceNeovim is probably that SpaceNeovim only focuses on a distribution mode, while spacevim also supports just having keybindings enabled. SpaceNeovim also has a more clear separation of layers vs core.
